name: Rust

on:
  push:
    branches: [ "master" ]
    paths: "src/**"
  pull_request:
    branches: [ "master" ]
    paths: "src/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set Timezone to Europe/Oslo
      uses: szenius/set-timezone@v2.0
      with:
        timezoneLinux: "Europe/Oslo"
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
